### I. Preparation of Python enviroment

### I.1. Modules import and data loading

#### I.1.1. Modules import

To carry out the work, the following modules will be needed:
1. pandas - for data handling and analysis,
2. scipy.stats - for calculating correlation and statistical significance coefficients,
3. numpy - for modifying array objects,
4. LinearRegression - for calculating linear regression coefficients.

In [1]:
import pandas as pd
import scipy.stats as sp
import numpy as np
from sklearn.linear_model import LinearRegression

#### I.1.2. Data loading

Data from "dataset.csv" file will be loaded to a Dataframe object of the Pandas library.

In [2]:
dataset_df = pd.DataFrame()
dataset_df = pd.read_csv(r'C:\Users\Sebastian\Documents\Data Analyst\Portfolio\1\bi_to_python_countries_data.csv')

To test the correct loading of the data, the top and bottom rows of the Dataframe object will be displayed.

In [3]:
dataset_df.head()

,location,location_id,year,total_kcal,carbohydrates,protein,fat,lex,lex_females,lex_males
0,Afghanistan,4,1961,2999,2321.77,339.64,337.59,33.0681,33.8128,32.4086
1,Afghanistan,4,1962,2917,2246.59,331.92,338.49,33.5471,34.2969,32.8833
2,Afghanistan,4,1963,2698,2042.39,308.48,347.13,34.0162,34.7731,33.3461
3,Afghanistan,4,1964,2953,2268.49,333.96,350.55,34.4942,35.2464,33.8282
4,Afghanistan,4,1965,2956,2262.99,335.44,357.57,34.9528,35.7021,34.2889

In [4]:
dataset_df.tail()

,location,location_id,year,total_kcal,carbohydrates,protein,fat,lex,lex_females,lex_males
9638,Zambia,894,2015,2130,1413.80,240.28,475.92,61.2078,63.5089,58.7850
9639,Zambia,894,2016,2181,1496.62,239.96,444.42,61.7937,64.1205,59.3493
9640,Zambia,894,2017,2232,1540.95,234.48,456.57,62.1201,64.6084,59.5269
9641,Zambia,894,2018,2254,1553.63,232.28,468.09,62.3422,64.9158,59.6741
9642,Zambia,894,2019,2267,1527.27,243.56,496.17,62.7926,65.4095,60.0801

The size of the dataset_df object will be checked out.

In [5]:
import sys
print(sys.getsizeof(dataset_df))

1268890

The dataset_df object takes up almost 1.5 MB of memory, so it can be processed and analysed locally.

A list of unique countries will be created to allow further work with the Country class.
The lenght of the country list will be calculated.

In [6]:
countries_list = dataset_df['location_id'].unique().tolist()
len(countries_list)

188

### I.2. The creation of a Country class

For easier data management, a Country class will be defined, with the attributes as follow:
1. *country_name* - an information about a name of the country, as string,
2. *country_data* - an information about a annual caloric supply per capita and a life expectancy in a given country, as dataframe,
3. *correlation* - an information about the Pearson's correlation coefficient for the relationship between caloric supply and life expectancy, rounded up to 2 decimal places,
4. *p_factor* - an information about the statistical significance coefficient (p), rounded up to 2 decimal places,
5. *a* - an information about the coefficient of linear regression function y = a*x + b, rounded to 4 decimal places,
6. *b* - an information about the coefficient of linear regression function y = a*x + b, rounded to 4 decimal places,.

For each combination of the source data (i.e. caloric supply and life expectancy), a *stats* methods will be defined for the Country class, with following attributes:
1. *country* - a method extracting data from the source file and storing it into *country_data* attribute,
2. *correlation* - a method calculating the Pearson's correlation coefficient for the parameters concerned,
3. *p_value* - a method calculating the statistical significance coefficient for the parameters concerned,
4. *regr_a* - a method calculating the coefficient *a* of linear regression,
5. *regr_b* - a method calculating the coefficient *b* of linear regression.

The instances of the Country class will be stored in a dictionary, where the key will be consecutive natural numbers and the value will be the instances of the class.

In [7]:
# creation of the Country class
class Country:

    # definition of country attributes
    def __init__(self, country_name = None, country_id = None, country_data = None,
                 correlation_tlex = None, correlation_clex = None, correlation_plex = None, correlation_flex = None,
                 correlation_tlexf = None, correlation_clexf = None, correlation_plexf = None, correlation_flexf = None,
                 correlation_tlexm = None, correlation_clexm = None, correlation_plexm = None, correlation_flexm = None,
                 p_value_tlex = None, p_value_clex = None, p_value_plex = None, p_value_flex = None,
                 p_value_tlexf = None, p_value_clexf = None, p_value_plexf = None, p_value_flexf = None,
                 p_value_tlexm = None, p_value_clexm = None, p_value_plexm = None, p_value_flexm = None,
                 regr_a_tlex = None, regr_b_tlex = None,
                 regr_a_tlexf = None, regr_b_tlexf = None,
                 regr_a_tlexm = None, regr_b_tlexm = None):
        self.country_name = country_name
        self.country_id = country_id
        self.country_data = country_data
        self.correlation_tlex = correlation_tlex
        self.correlation_clex = correlation_clex
        self.correlation_plex = correlation_plex
        self.correlation_flex = correlation_flex
        self.correlation_tlexf = correlation_tlexf
        self.correlation_clexf = correlation_clexf
        self.correlation_plexf = correlation_plexf
        self.correlation_flexf = correlation_flexf
        self.correlation_tlexm = correlation_tlexm
        self.correlation_clexm = correlation_plexm
        self.correlation_plexm = correlation_clexm
        self.correlation_flexm = correlation_flexm
        self.p_value_tlex = p_value_tlex
        self.p_value_clex = p_value_clex
        self.p_value_plex = p_value_plex
        self.p_value_flex = p_value_flex
        self.p_value_tlexf = p_value_tlexf
        self.p_value_clexf = p_value_clexf
        self.p_value_plexf = p_value_plexf
        self.p_value_flexf = p_value_flexf
        self.p_value_tlexm = p_value_tlexm
        self.p_value_clexm = p_value_clexm
        self.p_value_plexm = p_value_plexm
        self.p_value_flexm = p_value_flexm
        self.regr_a_tlex = regr_a_tlex
        self.regr_b_tlex = regr_b_tlex
        self.regr_a_tlexf = regr_a_tlexf
        self.regr_b_tlexf = regr_b_tlexf
        self.regr_a_tlexm = regr_a_tlexm
        self.regr_b_tlexm = regr_b_tlexm
        
    # definition of stats method for data_tlex
    def stats_tlex(self):
        tempdf = self.country_data
        tempdf = tempdf[['total_kcal', 'lex']]
        corr_coef_tlex, p_value_tlex = sp.pearsonr(tempdf['total_kcal'], tempdf['lex'])
        self.correlation_tlex = round(corr_coef_tlex, 2)
        self.p_value_tlex = round(p_value_tlex, 2)
               
        x = np.array(tempdf['total_kcal']).reshape(-1, 1)
        y = tempdf['lex']
        tempmodel = LinearRegression().fit(x, y)
        pre_regr_a_tlex = tempmodel.coef_
        regr_a_tlex = round(pre_regr_a_tlex[0], 4)
        regr_b_tlex = round(tempmodel.intercept_, 4)
        self.regr_a_tlex = regr_a_tlex
        self.regr_b_tlex = regr_b_tlex
                
    # definition of stats method for data_clex
    def stats_clex(self):
        tempdf = self.country_data
        tempdf = tempdf[['carbohydrates', 'lex']]
        corr_coef_clex, p_value_clex = sp.pearsonr(tempdf['carbohydrates'], tempdf['lex'])
        self.correlation_clex = round(corr_coef_clex, 2)
        self.p_value_clex = round(p_value_clex, 2)
        
    # definition of stats method for data_plex
    def stats_plex(self):
        tempdf = self.country_data
        tempdf = tempdf[['protein', 'lex']]
        corr_coef_plex, p_value_plex = sp.pearsonr(tempdf['protein'], tempdf['lex'])
        self.correlation_plex = round(corr_coef_plex, 2)
        self.p_value_plex = round(p_value_plex, 2) 
    
    # definition of stats method for data_flex
    def stats_flex(self):
        tempdf = self.country_data
        tempdf = tempdf[['fat', 'lex']]
        corr_coef_flex, p_value_flex = sp.pearsonr(tempdf['fat'], tempdf['lex'])
        self.correlation_flex = round(corr_coef_flex, 2)
        self.p_value_flex = round(p_value_flex, 2)
    
    # definition of stats method for data_tlexf
    def stats_tlexf(self):
        tempdf = self.country_data
        tempdf = tempdf[['total_kcal', 'lex_females']]
        corr_coef_tlexf, p_value_tlexf = sp.pearsonr(tempdf['total_kcal'], tempdf['lex_females'])
        self.correlation_tlexf = round(corr_coef_tlexf, 2)
        self.p_value_tlexf = round(p_value_tlexf, 2)
        
        x = np.array(tempdf['total_kcal']).reshape(-1, 1)
        y = tempdf['lex_females']
        tempmodel = LinearRegression().fit(x, y)
        pre_regr_a_tlexf = tempmodel.coef_
        regr_a_tlexf = round(pre_regr_a_tlexf[0], 4)
        regr_b_tlexf = round(tempmodel.intercept_, 4)
        self.regr_a_tlexf = regr_a_tlexf
        self.regr_b_tlexf = regr_b_tlexf
                
    # definition of stats method for data_clexf
    def stats_clexf(self):
        tempdf = self.country_data
        tempdf = tempdf[['carbohydrates', 'lex_females']]
        corr_coef_clexf, p_value_clexf = sp.pearsonr(tempdf['carbohydrates'], tempdf['lex_females'])
        self.correlation_clexf = round(corr_coef_clexf, 2)
        self.p_value_clexf = round(p_value_clexf, 2)
    
    # Metoda populująca atrybut data_plexf
    def stats_plexf(self):
        tempdf = self.country_data
        tempdf = tempdf[['protein', 'lex_females']]
        corr_coef_plexf, p_value_plexf = sp.pearsonr(tempdf['protein'], tempdf['lex_females'])
        self.correlation_plexf = round(corr_coef_plexf, 2)
        self.p_value_plexf = round(p_value_plexf, 2) 
    
    # definition of stats method for data_flexf
    def stats_flexf(self):
        tempdf = self.country_data
        tempdf = tempdf[['fat', 'lex_females']]
        corr_coef_flexf, p_value_flexf = sp.pearsonr(tempdf['fat'], tempdf['lex_females'])
        self.correlation_flexf = round(corr_coef_flexf, 2)
        self.p_value_flexf = round(p_value_flexf, 2)
        
    # definition of stats method for data_tlexm
    def stats_tlexm(self):
        tempdf = self.country_data
        tempdf = tempdf[['total_kcal', 'lex_males']]
        corr_coef_tlexm, p_value_tlexm = sp.pearsonr(tempdf['total_kcal'], tempdf['lex_males'])
        self.correlation_tlexm = round(corr_coef_tlexm, 2)
        self.p_value_tlexm = round(p_value_tlexm, 2)
        
        x = np.array(tempdf['total_kcal']).reshape(-1, 1)
        y = tempdf['lex_males']
        tempmodel = LinearRegression().fit(x, y)
        pre_regr_a_tlexm = tempmodel.coef_
        regr_a_tlexm = round(pre_regr_a_tlexm[0], 4)
        regr_b_tlexm = round(tempmodel.intercept_, 4)
        self.regr_a_tlexm = regr_a_tlexm
        self.regr_b_tlexm = regr_b_tlexm
                
    # definition of stats method for data_clexm
    def stats_clexm(self):
        tempdf = self.country_data
        tempdf = tempdf[['carbohydrates', 'lex_males']]
        corr_coef_clexm, p_value_clexm = sp.pearsonr(tempdf['carbohydrates'], tempdf['lex_males'])
        self.correlation_clexm = round(corr_coef_clexm, 2)
        self.p_value_clexm = round(p_value_clexm, 2)
    
    # definition of stats method for data_plexm
    def stats_plexm(self):
        tempdf = self.country_data
        tempdf = tempdf[['protein', 'lex_males']]
        corr_coef_plexm, p_value_plexm = sp.pearsonr(tempdf['protein'], tempdf['lex_males'])
        self.correlation_plexm = round(corr_coef_plexm, 2)
        self.p_value_plexm = round(p_value_plexm, 2) 
    
    # definition of stats method for data_flexm
    def stats_flexm(self):
        tempdf = self.country_data
        tempdf = tempdf[['fat', 'lex_males']]
        corr_coef_flexm, p_value_flexm = sp.pearsonr(tempdf['fat'], tempdf['lex_males'])
        self.correlation_flexm = round(corr_coef_flexm, 2)
        self.p_value_flexm = round(p_value_flexm, 2)

In [8]:
countries_dict = {}
for i in countries_list:
    countries_dict[i] = Country()

print(countries_dict)

{4: <__main__.Country object at 0x0000022F635F2240>, 8: <__main__.Country object at 0x0000022F6339BEC0>, 12: <__main__.Country object at 0x0000022F6346AA80>, 24: <__main__.Country object at 0x0000022F6274BF80>, 28: <__main__.Country object at 0x0000022F6274AB40>, 31: <__main__.Country object at 0x0000022F635F2270>, 32: <__main__.Country object at 0x0000022F635F22D0>, 36: <__main__.Country object at 0x0000022F635F2C90>, 40: <__main__.Country object at 0x0000022F635F2BA0>, 44: <__main__.Country object at 0x0000022F635F2D20>, 50: <__main__.Country object at 0x0000022F635F2CF0>, 51: <__main__.Country object at 0x0000022F635F2C60>, 52: <__main__.Country object at 0x0000022F635F2D50>, 56: <__main__.Country object at 0x0000022F635F2D80>, 58: <__main__.Country object at 0x0000022F635F2DB0>, 60: <__main__.Country object at 0x0000022F635F2DE0>, 68: <__main__.Country object at 0x0000022F635F2E10>, 70: <__main__.Country object at 0x0000022F635F2E40>, 72: <__main__.Country object at 0x0000022F635F2E70>, 76: <__main__.Country object at 0x0000022F635F2EA0>, 84: <__main__.Country object at 0x0000022F635F2ED0>, 90: <__main__.Country object at 0x0000022F635F2F00>, 96: <__main__.Country object at 0x0000022F635F2F30>, 100: <__main__.Country object at 0x0000022F635F2F60>, 104: <__main__.Country object at 0x0000022F635F2F90>, 108: <__main__.Country object at 0x0000022F635F2FF0>, 112: <__main__.Country object at 0x0000022F635F2FC0>, 116: <__main__.Country object at 0x0000022F635F3020>, 120: <__main__.Country object at 0x0000022F635F3050>, 124: <__main__.Country object at 0x0000022F635F3080>, 132: <__main__.Country object at 0x0000022F635F30B0>, 140: <__main__.Country object at 0x0000022F635F30E0>, 144: <__main__.Country object at 0x0000022F635F3110>, 148: <__main__.Country object at 0x0000022F635F3140>, 152: <__main__.Country object at 0x0000022F635F3170>, 156: <__main__.Country object at 0x0000022F635F31A0>, 158: <__main__.Country object at 0x0000022F635F31D0>, 170: <__main__.Country object at 0x0000022F635F3200>, 174: <__main__.Country object at 0x0000022F635F3230>, 178: <__main__.Country object at 0x0000022F635F3260>, 180: <__main__.Country object at 0x0000022F635F3290>, 188: <__main__.Country object at 0x0000022F635F32C0>, 191: <__main__.Country object at 0x0000022F635F32F0>, 192: <__main__.Country object at 0x0000022F635F3320>, 196: <__main__.Country object at 0x0000022F635F3350>, 200: <__main__.Country object at 0x0000022F635F3380>, 203: <__main__.Country object at 0x0000022F635F33B0>, 204: <__main__.Country object at 0x0000022F635F33E0>, 208: <__main__.Country object at 0x0000022F635F3410>, 212: <__main__.Country object at 0x0000022F635F3440>, 214: <__main__.Country object at 0x0000022F635F3470>, 218: <__main__.Country object at 0x0000022F635F34A0>, 222: <__main__.Country object at 0x0000022F635F34D0>, 231: <__main__.Country object at 0x0000022F635F3500>, 233: <__main__.Country object at 0x0000022F635F3530>, 242: <__main__.Country object at 0x0000022F635F3560>, 246: <__main__.Country object at 0x0000022F635F3590>, 250: <__main__.Country object at 0x0000022F635F35C0>, 258: <__main__.Country object at 0x0000022F635F35F0>, 262: <__main__.Country object at 0x0000022F635F3620>, 266: <__main__.Country object at 0x0000022F635F3650>, 268: <__main__.Country object at 0x0000022F635F3680>, 270: <__main__.Country object at 0x0000022F635F36B0>, 276: <__main__.Country object at 0x0000022F635F36E0>, 288: <__main__.Country object at 0x0000022F635F3710>, 296: <__main__.Country object at 0x0000022F635F3740>, 300: <__main__.Country object at 0x0000022F635F37A0>, 308: <__main__.Country object at 0x0000022F635F3770>, 320: <__main__.Country object at 0x0000022F635F37D0>, 324: <__main__.Country object at 0x0000022F635F3800>, 328: <__main__.Country object at 0x0000022F635F3830>, 332: <__main__.Country object at 0x0000022F635F3860>, 340: <__main__.Country object at 0x0000022F635F3890>, 344: <__main__.Country object at 0x0000022F635F38C0>, 348: <__main__.Country object at 0x0000022F635F38F0>, 352: <__main__.Country object at 0x0000022F635F3920>, 356: <__main__.Country object at 0x0000022F635F3950>, 360: <__main__.Country object at 0x0000022F635F3980>, 364: <__main__.Country object at 0x0000022F635F39B0>, 368: <__main__.Country object at 0x0000022F635F39E0>, 372: <__main__.Country object at 0x0000022F635F3A10>, 376: <__main__.Country object at 0x0000022F635F3A40>, 380: <__main__.Country object at 0x0000022F635F3A70>, 384: <__main__.Country object at 0x0000022F635F3AA0>, 388: <__main__.Country object at 0x0000022F635F3B00>, 392: <__main__.Country object at 0x0000022F635F3AD0>, 398: <__main__.Country object at 0x0000022F635F3B30>, 400: <__main__.Country object at 0x0000022F635F3B60>, 404: <__main__.Country object at 0x0000022F635F3B90>, 408: <__main__.Country object at 0x0000022F635F3BC0>, 410: <__main__.Country object at 0x0000022F635F3BF0>, 414: <__main__.Country object at 0x0000022F635F3C20>, 417: <__main__.Country object at 0x0000022F635F3C50>, 418: <__main__.Country object at 0x0000022F635F3C80>, 422: <__main__.Country object at 0x0000022F635F3CB0>, 426: <__main__.Country object at 0x0000022F635F3CE0>, 428: <__main__.Country object at 0x0000022F635F3D10>, 430: <__main__.Country object at 0x0000022F635F3D70>, 434: <__main__.Country object at 0x0000022F635F3DA0>, 440: <__main__.Country object at 0x0000022F635F3DD0>, 442: <__main__.Country object at 0x0000022F635F3E00>, 446: <__main__.Country object at 0x0000022F635F3E30>, 450: <__main__.Country object at 0x0000022F635F3E60>, 454: <__main__.Country object at 0x0000022F635F3E90>, 458: <__main__.Country object at 0x0000022F635F3EC0>, 462: <__main__.Country object at 0x0000022F635F3EF0>, 466: <__main__.Country object at 0x0000022F635F3F20>, 470: <__main__.Country object at 0x0000022F635F3F50>, 478: <__main__.Country object at 0x0000022F635F3F80>, 480: <__main__.Country object at 0x0000022F635F3FB0>, 484: <__main__.Country object at 0x0000022F635F3FE0>, 496: <__main__.Country object at 0x0000022F635F2000>, 498: <__main__.Country object at 0x0000022F635F2480>, 499: <__main__.Country object at 0x0000022F635F2420>, 504: <__main__.Country object at 0x0000022F635F2450>, 508: <__main__.Country object at 0x0000022F635F2540>, 512: <__main__.Country object at 0x0000022F635F24E0>, 516: <__main__.Country object at 0x0000022F635F2510>, 524: <__main__.Country object at 0x0000022F64628050>, 528: <__main__.Country object at 0x0000022F64628320>, 530: <__main__.Country object at 0x0000022F646288F0>, 540: <__main__.Country object at 0x0000022F64628AA0>, 548: <__main__.Country object at 0x0000022F64628DD0>, 554: <__main__.Country object at 0x0000022F64628E60>, 558: <__main__.Country object at 0x0000022F64628FB0>, 562: <__main__.Country object at 0x0000022F64629040>, 566: <__main__.Country object at 0x0000022F64629370>, 578: <__main__.Country object at 0x0000022F646293D0>, 586: <__main__.Country object at 0x0000022F64629550>, 591: <__main__.Country object at 0x0000022F646295B0>, 598: <__main__.Country object at 0x0000022F6462A750>, 600: <__main__.Country object at 0x0000022F6462A8D0>, 604: <__main__.Country object at 0x0000022F6462AC60>, 608: <__main__.Country object at 0x0000022F6462ADE0>, 616: <__main__.Country object at 0x0000022F6462BF20>, 620: <__main__.Country object at 0x0000022F646299D0>, 624: <__main__.Country object at 0x0000022F64629A00>, 626: <__main__.Country object at 0x0000022F64628740>, 642: <__main__.Country object at 0x0000022F64628770>, 643: <__main__.Country object at 0x0000022F64628080>, 646: <__main__.Country object at 0x0000022F646280B0>, 659: <__main__.Country object at 0x0000022F646280E0>, 662: <__main__.Country object at 0x0000022F64628110>, 670: <__main__.Country object at 0x0000022F64628140>, 678: <__main__.Country object at 0x0000022F64628170>, 682: <__main__.Country object at 0x0000022F646281D0>, 686: <__main__.Country object at 0x0000022F646281A0>, 688: <__main__.Country object at 0x0000022F64628200>, 690: <__main__.Country object at 0x0000022F64628230>, 694: <__main__.Country object at 0x0000022F64628260>, 703: <__main__.Country object at 0x0000022F64628290>, 704: <__main__.Country object at 0x0000022F646282C0>, 705: <__main__.Country object at 0x0000022F646282F0>, 710: <__main__.Country object at 0x0000022F64628350>, 716: <__main__.Country object at 0x0000022F64628380>, 724: <__main__.Country object at 0x0000022F646283B0>, 729: <__main__.Country object at 0x0000022F646283E0>, 736: <__main__.Country object at 0x0000022F64628410>, 740: <__main__.Country object at 0x0000022F64628440>, 748: <__main__.Country object at 0x0000022F64628470>, 752: <__main__.Country object at 0x0000022F646284A0>, 756: <__main__.Country object at 0x0000022F646284D0>, 760: <__main__.Country object at 0x0000022F64628500>, 762: <__main__.Country object at 0x0000022F64628530>, 764: <__main__.Country object at 0x0000022F64628560>, 768: <__main__.Country object at 0x0000022F64628590>, 780: <__main__.Country object at 0x0000022F646285C0>, 784: <__main__.Country object at 0x0000022F646285F0>, 788: <__main__.Country object at 0x0000022F64628620>, 792: <__main__.Country object at 0x0000022F64628650>, 795: <__main__.Country object at 0x0000022F64628680>, 800: <__main__.Country object at 0x0000022F646286B0>, 804: <__main__.Country object at 0x0000022F646286E0>, 807: <__main__.Country object at 0x0000022F64628710>, 810: <__main__.Country object at 0x0000022F646287A0>, 818: <__main__.Country object at 0x0000022F646287D0>, 826: <__main__.Country object at 0x0000022F64628800>, 834: <__main__.Country object at 0x0000022F64628830>, 840: <__main__.Country object at 0x0000022F64628860>, 854: <__main__.Country object at 0x0000022F64628890>, 858: <__main__.Country object at 0x0000022F646288C0>, 860: <__main__.Country object at 0x0000022F64628920>, 862: <__main__.Country object at 0x0000022F64628950>, 882: <__main__.Country object at 0x0000022F646289B0>, 887: <__main__.Country object at 0x0000022F64628980>, 890: <__main__.Country object at 0x0000022F646289E0>, 891: <__main__.Country object at 0x0000022F64628A10>, 894: <__main__.Country object at 0x0000022F64628A40>}

Then, by iterating through the dictionary on key-value pairs, to the instances of the Country class will be assigned the corresponding values for a particular country, as attributes of these instances.

In [9]:
for key, value in countries_dict.items():
    temp_filter = dataset_df['location_id'] == key
    value.country_data = dataset_df[temp_filter]
    value.country_name = value.country_data['location'].unique()[0]
    value.country_id = value.country_data['location_id'].unique()[0]

In order to test the correct operation of the loop above, the attributes of Poland country will be shown.

In [10]:
countries_dict[616].country_data.head()

,location,location_id,year,total_kcal,carbohydrates,protein,fat,lex,lex_females,lex_males
7017,Poland,616,1961,3270,2088.77,386.08,795.15,67.9367,70.8064,64.8557
7018,Poland,616,1962,3273,2089.44,386.88,796.68,67.6365,70.5363,64.5455
7019,Poland,616,1963,3291,2085.39,391.20,814.41,68.5615,71.5218,65.4025
7020,Poland,616,1964,3304,2074.74,394.96,834.30,68.7841,71.6129,65.7483
7021,Poland,616,1965,3358,2094.24,403.72,860.04,69.4860,72.3612,66.3999

In [11]:
countries_dict[616].country_data.tail()

,location,location_id,year,total_kcal,carbohydrates,protein,fat,lex,lex_females,lex_males
7071,Poland,616,2015,3373,1868.01,403.48,1101.51,77.4151,81.3070,73.4696
7072,Poland,616,2016,3451,1919.96,415.76,1115.28,77.8025,81.7191,73.8273
7073,Poland,616,2017,3502,1963.90,421.20,1116.90,77.7205,81.5418,73.8484
7074,Poland,616,2018,3542,1966.42,423.76,1151.82,77.6282,81.4865,73.7447
7075,Poland,616,2019,3508,1978.73,419.84,1109.43,77.9272,81.7395,74.0824

In [12]:
print(countries_dict[616].country_name)

Poland

### II. The calculation of correlation coefficient and statistical significance coefficient

Country class method, i.e. stats, will be used for the calculation.

In [13]:
for key, value in countries_dict.items():
    value.stats_tlex()
    value.stats_clex()
    value.stats_plex()
    value.stats_flex()
    value.stats_tlexf()
    value.stats_clexf()
    value.stats_plexf()
    value.stats_flexf()
    value.stats_tlexm()
    value.stats_clexm()
    value.stats_plexm()
    value.stats_flexm()
    print(value.country_name, value.country_id,
          value.correlation_tlex, value.p_value_tlex, value.regr_a_tlex, value.regr_b_tlex,
          value.correlation_clex, value.p_value_clex,
          value.correlation_plex, value.p_value_plex,
          value.correlation_flex, value.p_value_flex,
          value.correlation_tlexf, value.p_value_tlexf, value.regr_a_tlexf, value.regr_b_tlexf,
          value.correlation_clexf, value.p_value_clexf,
          value.correlation_plexf, value.p_value_plexf,
          value.correlation_flexf, value.p_value_flexf,
          value.correlation_tlexm, value.p_value_tlexm, value.regr_a_tlexm, value.regr_b_tlexm,
          value.correlation_clexm, value.p_value_clexm,
          value.correlation_plexm, value.p_value_plexm,
          value.correlation_flexm, value.p_value_flexm)

Afghanistan 4 -0.77 0.0 -0.0218 98.6684 -0.74 0.0 -0.86 0.0 -0.5 0.0 -0.78 0.0 -0.0223 101.6533 -0.75 0.0 -0.87 0.0 -0.45 0.0 -0.76 0.0 -0.0211 95.4887 -0.72 0.0 -0.84 0.0 -0.54 0.0
Albania 8 0.89 0.0 0.018 22.78 0.52 0.0 0.89 0.0 0.86 0.0 0.88 0.0 0.0178 26.1165 0.5 0.0 0.88 0.0 0.85 0.0 0.9 0.0 0.0183 19.2219 0.53 0.0 0.89 0.0 0.87 0.0
Algeria 12 0.97 0.0 0.0207 8.0353 0.97 0.0 0.98 0.0 0.91 0.0 0.97 0.0 0.0209 8.6734 0.97 0.0 0.98 0.0 0.91 0.0 0.97 0.0 0.0204 7.5202 0.97 0.0 0.98 0.0 0.91 0.0
Angola 24 0.84 0.0 0.0233 0.9695 0.68 0.0 0.83 0.0 0.9 0.0 0.83 0.0 0.0221 6.1747 0.66 0.0 0.83 0.0 0.91 0.0 0.85 0.0 0.0241 -3.2383 0.69 0.0 0.83 0.0 0.89 0.0
Antigua and Barbuda 28 0.43 0.0 0.0075 56.798 -0.29 0.03 0.69 0.0 0.69 0.0 0.43 0.0 0.0076 59.1613 -0.29 0.02 0.69 0.0 0.69 0.0 0.45 0.0 0.0078 53.4426 -0.28 0.03 0.71 0.0 0.71 0.0
Azerbaijan 31 0.95 0.0 0.0087 43.8774 0.91 0.0 0.95 0.0 0.95 0.0 0.95 0.0 0.0077 50.2183 0.91 0.0 0.95 0.0 0.95 0.0 0.94 0.0 0.0097 37.548 0.91 0.0 0.94 0.0 0.94 0.0
Argentina 32 0.12 0.38 0.005 55.2117 -0.27 0.04 -0.08 0.54 0.45 0.0 0.14 0.29 0.0056 57.112 -0.26 0.05 -0.06 0.63 0.47 0.0 0.11 0.42 0.0047 52.7662 -0.27 0.04 -0.09 0.5 0.43 0.0
Australia 36 0.48 0.0 0.0188 17.8325 -0.87 0.0 -0.28 0.03 0.92 0.0 0.45 0.0 0.0154 31.4498 -0.88 0.0 -0.3 0.02 0.91 0.0 0.51 0.0 0.0219 5.2069 -0.86 0.0 -0.27 0.04 0.94 0.0
Austria 40 0.97 0.0 0.0195 7.7875 0.45 0.0 0.94 0.0 0.91 0.0 0.97 0.0 0.0182 15.5691 0.42 0.0 0.94 0.0 0.92 0.0 0.96 0.0 0.0211 -0.9199 0.48 0.0 0.93 0.0 0.89 0.0
Bahamas 44 0.51 0.0 0.0112 40.7091 -0.37 0.0 0.68 0.0 0.81 0.0 0.51 0.0 0.0115 43.2477 -0.37 0.0 0.67 0.0 0.81 0.0 0.51 0.0 0.0107 38.6462 -0.38 0.0 0.68 0.0 0.81 0.0
Bangladesh 50 0.79 0.0 0.04 -30.0858 0.67 0.0 0.8 0.0 0.91 0.0 0.84 0.0 0.0458 -42.4828 0.72 0.0 0.84 0.0 0.94 0.0 0.74 0.0 0.0347 -18.4656 0.62 0.0 0.75 0.0 0.86 0.0
Armenia 51 0.96 0.0 0.0057 57.0414 0.58 0.0 0.97 0.0 0.97 0.0 0.96 0.0 0.0066 58.6568 0.59 0.0 0.97 0.0 0.97 0.0 0.94 0.0 0.0044 56.042 0.57 0.0 0.95 0.0 0.95 0.0
Barbados 52 0.55 0.0 0.0128 35.5605 -0.39 0.0 0.78 0.0 0.65 0.0 0.57 0.0 0.0136 35.3592 -0.41 0.0 0.8 0.0 0.69 0.0 0.53 0.0 0.0127 33.4054 -0.36 0.0 0.77 0.0 0.62 0.0
Belgium 56 0.62 0.0 0.0223 -3.3361 0.36 0.12 -0.1 0.67 0.41 0.08 0.62 0.0 0.0171 18.5503 0.36 0.12 -0.1 0.69 0.4 0.08 0.63 0.0 0.0277 -26.2024 0.36 0.12 -0.1 0.66 0.41 0.07
Belgium-Luxembourg 58 0.97 0.0 0.0104 39.1565 0.92 0.0 0.91 0.0 0.95 0.0 0.97 0.0 0.0106 41.7382 0.92 0.0 0.93 0.0 0.95 0.0 0.96 0.0 0.0099 37.5438 0.92 0.0 0.9 0.0 0.95 0.0
Bermuda 60 -0.12 0.4 -0.0036 83.9949 -0.12 0.38 -0.28 0.04 0.01 0.94 -0.07 0.64 -0.0021 83.4897 -0.11 0.41 -0.23 0.1 0.09 0.54 -0.16 0.25 -0.0047 83.6363 -0.13 0.34 -0.33 0.02 -0.05 0.72
Bolivia (Plurinational State of) 68 0.76 0.0 0.037 -20.1302 0.71 0.0 0.83 0.0 0.68 0.0 0.77 0.0 0.0387 -21.8102 0.7 0.0 0.84 0.0 0.68 0.0 0.76 0.0 0.0356 -19.0281 0.71 0.0 0.82 0.0 0.67 0.0
Bosnia and Herzegovina 70 0.83 0.0 0.0221 7.4723 0.81 0.0 0.74 0.0 0.76 0.0 0.81 0.0 0.0127 39.0823 0.78 0.0 0.72 0.0 0.75 0.0 0.85 0.0 0.0281 -13.7913 0.82 0.0 0.75 0.0 0.78 0.0
Botswana 72 0.56 0.0 0.0143 26.8118 0.62 0.0 0.09 0.48 0.44 0.0 0.53 0.0 0.0143 29.3486 0.59 0.0 0.13 0.34 0.4 0.0 0.6 0.0 0.0147 23.5079 0.66 0.0 0.05 0.73 0.49 0.0
Brazil 76 0.98 0.0 0.0204 8.9624 0.38 0.0 0.93 0.0 0.98 0.0 0.98 0.0 0.0214 8.9553 0.36 0.0 0.94 0.0 0.98 0.0 0.98 0.0 0.0192 9.4238 0.39 0.0 0.93 0.0 0.98 0.0
Belize 84 0.84 0.0 0.0187 20.1606 0.72 0.0 0.7 0.0 0.79 0.0 0.85 0.0 0.0209 16.8426 0.74 0.0 0.72 0.0 0.78 0.0 0.82 0.0 0.0171 22.358 0.69 0.0 0.68 0.0 0.79 0.0
Solomon Islands 90 0.57 0.0 0.0338 -14.3784 0.36 0.01 0.28 0.03 0.48 0.0 0.5 0.0 0.0306 -4.6437 0.28 0.03 0.29 0.02 0.52 0.0 0.61 0.0 0.0352 -19.528 0.4 0.0 0.27 0.04 0.46 0.0
Brunei Darussalam 96 0.93 0.0 0.0129 36.3698 0.89 0.0 0.93 0.0 0.92 0.0 0.94 0.0 0.0151 32.167 0.9 0.0 0.95 0.0 0.94 0.0 0.91 0.0 0.011 39.8799 0.88 0.0 0.91 0.0 0.9 0.0
Bulgaria 100 -0.57 0.0 -0.0022 78.9451 -0.64 0.0 -0.54 0.0 0.12 0.38 -0.66 0.0 -0.0034 85.7808 -0.79 0.0 -0.58 0.0 0.23 0.07 -0.32 0.01 -0.001 72.2659 -0.31 0.02 -0.38 0.0 -0.06 0.66
Myanmar 104 0.87 0.0 0.0114 35.3965 0.89 0.0 0.82 0.0 0.82 0.0 0.86 0.0 0.0121 36.6426 0.89 0.0 0.81 0.0 0.8 0.0 0.88 0.0 0.0107 34.2629 0.9 0.0 0.83 0.0 0.83 0.0
Burundi 108 0.7 0.12 0.0132 38.1561 0.62 0.19 0.9 0.02 -0.25 0.64 0.74 0.09 0.0158 35.5039 0.68 0.13 0.88 0.02 -0.32 0.54 0.63 0.18 0.0107 40.6548 0.53 0.28 0.89 0.02 -0.16 0.76
Belarus 112 0.56 0.0 0.0088 42.9022 -0.45 0.02 -0.11 0.59 0.91 0.0 0.56 0.0 0.007 54.2245 -0.48 0.01 -0.14 0.46 0.94 0.0 0.55 0.0 0.0097 34.5459 -0.44 0.02 -0.1 0.62 0.89 0.0
Cambodia 116 0.84 0.0 0.0362 -21.9533 0.81 0.0 0.82 0.0 0.84 0.0 0.84 0.0 0.0335 -13.0707 0.81 0.0 0.83 0.0 0.83 0.0 0.84 0.0 0.0382 -29.0553 0.81 0.0 0.82 0.0 0.86 0.0
Cameroon 120 0.65 0.0 0.0143 20.1335 0.57 0.0 0.51 0.0 0.8 0.0 0.67 0.0 0.014 22.27 0.59 0.0 0.53 0.0 0.8 0.0 0.64 0.0 0.0146 18.231 0.55 0.0 0.49 0.0 0.79 0.0
Canada 124 0.92 0.0 0.0128 36.4741 0.74 0.0 0.84 0.0 0.97 0.0 0.89 0.0 0.0104 46.7939 0.7 0.0 0.82 0.0 0.96 0.0 0.93 0.0 0.0144 28.4326 0.76 0.0 0.85 0.0 0.98 0.0
Cabo Verde 132 0.91 0.0 0.0192 22.148 0.89 0.0 0.88 0.0 0.81 0.0 0.89 0.0 0.0217 18.6766 0.88 0.0 0.86 0.0 0.79 0.0 0.92 0.0 0.0164 26.0075 0.9 0.0 0.9 0.0 0.83 0.0
Central African Republic 140 -0.37 0.0 -0.0064 61.1263 -0.53 0.0 0.48 0.0 0.51 0.0 -0.4 0.0 -0.0075 64.8472 -0.54 0.0 0.45 0.0 0.46 0.0 -0.35 0.01 -0.0057 58.2418 -0.53 0.0 0.51 0.0 0.55 0.0
Sri Lanka 144 0.63 0.0 0.0157 33.2223 0.65 0.0 0.73 0.0 0.16 0.23 0.57 0.0 0.0173 33.3184 0.59 0.0 0.69 0.0 0.09 0.51 0.66 0.0 0.0131 35.9842 0.67 0.0 0.72 0.0 0.22 0.1
Chad 148 0.13 0.33 0.0021 41.1645 -0.09 0.47 0.19 0.16 0.45 0.0 0.07 0.6 0.0011 44.9303 -0.14 0.3 0.13 0.32 0.38 0.0 0.18 0.18 0.0031 37.6139 -0.06 0.65 0.23 0.08 0.51 0.0
Chile 152 0.73 0.0 0.0295 -9.3126 -0.14 0.28 0.79 0.0 0.86 0.0 0.72 0.0 0.0287 -4.1179 -0.16 0.23 0.77 0.0 0.85 0.0 0.75 0.0 0.0299 -13.2306 -0.12 0.35 0.8 0.0 0.87 0.0
China 156 0.97 0.0 0.0155 28.7905 0.96 0.0 0.92 0.0 0.92 0.0 0.97 0.0 0.0159 29.9997 0.96 0.0 0.92 0.0 0.92 0.0 0.97 0.0 0.015 27.5824 0.96 0.0 0.92 0.0 0.92 0.0
China (Taiwan Province of China) 158 0.85 0.0 0.0197 17.7572 -0.88 0.0 0.87 0.0 0.92 0.0 0.85 0.0 0.0213 16.2117 -0.88 0.0 0.87 0.0 0.93 0.0 0.85 0.0 0.0186 18.3093 -0.88 0.0 0.87 0.0 0.92 0.0
Colombia 170 0.95 0.0 0.0181 22.375 0.76 0.0 0.91 0.0 0.96 0.0 0.96 0.0 0.0202 20.2815 0.8 0.0 0.91 0.0 0.96 0.0 0.92 0.0 0.0162 24.1718 0.72 0.0 0.9 0.0 0.96 0.0
Comoros 174 0.0 1.0 0.0 63.3302 0.65 0.17 0.38 0.45 -0.79 0.06 0.02 0.97 0.0008 63.7238 0.67 0.15 0.34 0.51 -0.77 0.07 -0.03 0.96 -0.0008 63.1717 0.61 0.2 0.42 0.41 -0.79 0.06
Congo 178 0.53 0.0 0.0226 9.0804 0.22 0.1 0.76 0.0 0.32 0.01 0.45 0.0 0.0178 21.081 0.23 0.07 0.65 0.0 0.2 0.13 0.57 0.0 0.0271 -2.1396 0.2 0.13 0.81 0.0 0.4 0.0
Democratic Republic of the Congo 180 -0.44 0.38 -0.0249 107.2855 0.16 0.76 -0.78 0.07 -0.86 0.03 -0.51 0.31 -0.0313 121.3708 0.08 0.88 -0.8 0.06 -0.86 0.03 -0.36 0.48 -0.019 94.1075 0.25 0.64 -0.74 0.09 -0.85 0.03
Costa Rica 188 0.97 0.0 0.0203 20.8391 0.9 0.0 0.93 0.0 0.88 0.0 0.98 0.0 0.0208 21.7902 0.9 0.0 0.94 0.0 0.89 0.0 0.97 0.0 0.0197 20.1914 0.9 0.0 0.92 0.0 0.87 0.0
Croatia 191 0.88 0.0 0.0057 59.4673 0.54 0.0 0.96 0.0 0.89 0.0 0.88 0.0 0.0046 66.1234 0.53 0.0 0.95 0.0 0.89 0.0 0.88 0.0 0.0069 52.7339 0.55 0.0 0.96 0.0 0.89 0.0
Cuba 192 0.81 0.0 0.0084 49.1423 0.88 0.0 0.72 0.0 0.04 0.76 0.8 0.0 0.0088 50.3484 0.87 0.0 0.71 0.0 0.02 0.85 0.82 0.0 0.008 48.4484 0.88 0.0 0.74 0.0 0.06 0.65
Cyprus 196 0.3 0.02 0.0081 51.6835 -0.29 0.02 0.57 0.0 0.78 0.0 0.27 0.04 0.0058 60.6203 -0.34 0.01 0.57 0.0 0.78 0.0 0.31 0.02 0.0097 45.0029 -0.27 0.04 0.55 0.0 0.75 0.0
Czechoslovakia 200 0.21 0.25 0.0013 66.2766 -0.47 0.01 0.29 0.11 0.57 0.0 0.27 0.14 0.0024 65.9358 -0.66 0.0 0.47 0.01 0.75 0.0 0.06 0.73 0.0003 66.0937 -0.06 0.76 -0.07 0.7 0.13 0.48
Czechia 203 0.41 0.03 0.0094 46.0634 -0.64 0.0 -0.54 0.0 0.89 0.0 0.41 0.03 0.0084 52.5242 -0.64 0.0 -0.54 0.0 0.9 0.0 0.41 0.04 0.0104 39.7185 -0.64 0.0 -0.55 0.0 0.89 0.0
Benin 204 0.9 0.0 0.0181 12.4752 0.89 0.0 0.9 0.0 0.6 0.0 0.87 0.0 0.0178 14.7098 0.85 0.0 0.86 0.0 0.58 0.0 0.93 0.0 0.0183 10.295 0.92 0.0 0.92 0.0 0.61 0.0
Denmark 208 0.79 0.0 0.0151 27.0664 0.77 0.0 0.85 0.0 -0.05 0.71 0.76 0.0 0.0133 35.4002 0.74 0.0 0.85 0.0 -0.09 0.5 0.81 0.0 0.0166 19.9478 0.79 0.0 0.83 0.0 -0.01 0.91
Dominica 212 0.7 0.0 0.0052 56.3047 0.67 0.0 0.69 0.0 0.73 0.0 0.74 0.0 0.0063 55.6779 0.72 0.0 0.73 0.0 0.77 0.0 0.66 0.0 0.0045 55.7888 0.63 0.0 0.66 0.0 0.7 0.0
Dominican Republic 214 0.82 0.0 0.0206 18.6364 0.38 0.0 0.8 0.0 0.93 0.0 0.83 0.0 0.0215 19.2597 0.38 0.0 0.81 0.0 0.94 0.0 0.82 0.0 0.0197 17.9795 0.38 0.0 0.79 0.0 0.92 0.0
Ecuador 218 0.71 0.0 0.0407 -25.4076 -0.64 0.0 0.7 0.0 0.98 0.0 0.69 0.0 0.0424 -26.807 -0.65 0.0 0.68 0.0 0.97 0.0 0.73 0.0 0.039 -23.9743 -0.63 0.0 0.71 0.0 0.98 0.0
El Salvador 222 0.89 0.0 0.0232 9.2223 0.85 0.0 0.92 0.0 0.9 0.0 0.96 0.0 0.0255 8.7949 0.94 0.0 0.95 0.0 0.95 0.0 0.8 0.0 0.0204 10.8601 0.75 0.0 0.88 0.0 0.83 0.0
Ethiopia 231 0.86 0.0 0.0265 0.5222 0.91 0.0 0.64 0.0 0.24 0.06 0.88 0.0 0.0273 1.1037 0.92 0.0 0.67 0.0 0.3 0.02 0.84 0.0 0.0258 -0.0852 0.9 0.0 0.6 0.0 0.19 0.15
Estonia 233 0.74 0.0 0.0121 36.287 0.28 0.15 0.55 0.0 0.73 0.0 0.77 0.0 0.01 47.8161 0.32 0.1 0.52 0.0 0.72 0.0 0.72 0.0 0.0134 26.9024 0.24 0.21 0.57 0.0 0.74 0.0
Fiji 242 0.7 0.0 0.0091 40.0409 0.09 0.48 0.92 0.0 0.76 0.0 0.62 0.0 0.0078 46.0547 -0.02 0.89 0.88 0.0 0.78 0.0 0.75 0.0 0.0097 36.3637 0.18 0.17 0.93 0.0 0.73 0.0
Finland 246 0.55 0.0 0.02 12.3754 -0.13 0.34 0.9 0.0 0.66 0.0 0.5 0.0 0.017 25.5623 -0.18 0.17 0.87 0.0 0.66 0.0 0.59 0.0 0.0234 -2.1841 -0.07 0.58 0.92 0.0 0.66 0.0
France 250 0.8 0.0 0.0245 -7.7298 -0.54 0.0 0.56 0.0 0.78 0.0 0.84 0.0 0.0243 -3.1631 -0.6 0.0 0.62 0.0 0.83 0.0 0.77 0.0 0.0245 -11.426 -0.49 0.0 0.51 0.0 0.74 0.0
French Polynesia 258 0.67 0.0 0.0557 -84.6119 -0.97 0.0 0.94 0.0 0.96 0.0 0.68 0.0 0.0596 -93.6064 -0.97 0.0 0.94 0.0 0.96 0.0 0.67 0.0 0.0521 -76.186 -0.97 0.0 0.93 0.0 0.96 0.0
Djibouti 262 0.76 0.0 0.0096 35.9222 0.7 0.0 0.76 0.0 0.81 0.0 0.77 0.0 0.0098 37.6688 0.71 0.0 0.76 0.0 0.81 0.0 0.76 0.0 0.0095 34.2092 0.7 0.0 0.76 0.0 0.82 0.0
Gabon 266 0.95 0.0 0.0159 20.2787 0.93 0.0 0.95 0.0 0.94 0.0 0.93 0.0 0.016 21.7625 0.91 0.0 0.94 0.0 0.92 0.0 0.96 0.0 0.016 18.5572 0.94 0.0 0.95 0.0 0.95 0.0
Georgia 268 0.75 0.0 0.0047 58.4135 0.52 0.0 0.52 0.0 0.92 0.0 0.7 0.0 0.0047 62.6743 0.46 0.01 0.46 0.01 0.89 0.0 0.79 0.0 0.0047 53.6533 0.58 0.0 0.58 0.0 0.93 0.0
Gambia 270 0.77 0.0 0.0286 -16.1587 0.63 0.0 0.61 0.0 0.63 0.0 0.77 0.0 0.0286 -14.5435 0.63 0.0 0.59 0.0 0.63 0.0 0.77 0.0 0.0286 -17.7083 0.64 0.0 0.63 0.0 0.62 0.0
Germany 276 0.89 0.0 0.0176 17.5301 0.75 0.0 0.88 0.0 0.9 0.0 0.9 0.0 0.0172 21.6721 0.74 0.0 0.88 0.0 0.91 0.0 0.88 0.0 0.0183 12.0948 0.75 0.0 0.87 0.0 0.87 0.0
Ghana 288 0.85 0.0 0.0097 32.7946 0.84 0.0 0.83 0.0 0.65 0.0 0.85 0.0 0.0093 35.3133 0.85 0.0 0.84 0.0 0.65 0.0 0.84 0.0 0.0099 30.6305 0.84 0.0 0.82 0.0 0.65 0.0
Kiribati 296 0.74 0.0 0.0229 -4.1501 0.85 0.0 0.9 0.0 -0.22 0.09 0.74 0.0 0.0232 -3.4489 0.85 0.0 0.9 0.0 -0.22 0.09 0.74 0.0 0.0223 -3.9847 0.85 0.0 0.9 0.0 -0.22 0.09
Greece 300 0.76 0.0 0.011 39.4981 -0.25 0.06 0.78 0.0 0.96 0.0 0.77 0.0 0.0119 39.0193 -0.24 0.07 0.8 0.0 0.96 0.0 0.75 0.0 0.0103 39.2268 -0.26 0.05 0.77 0.0 0.95 0.0
Grenada 308 0.86 0.0 0.0174 30.6872 0.38 0.0 0.88 0.0 0.92 0.0 0.86 0.0 0.0188 30.1098 0.38 0.0 0.88 0.0 0.92 0.0 0.84 0.0 0.0171 28.8513 0.37 0.0 0.86 0.0 0.9 0.0
Guatemala 320 0.88 0.0 0.0404 -28.9198 0.72 0.0 0.82 0.0 0.85 0.0 0.89 0.0 0.0442 -34.4973 0.75 0.0 0.81 0.0 0.84 0.0 0.87 0.0 0.0366 -23.1103 0.68 0.0 0.83 0.0 0.86 0.0
Guinea 324 0.88 0.0 0.0281 -18.2561 0.81 0.0 0.78 0.0 0.77 0.0 0.89 0.0 0.0276 -16.0165 0.81 0.0 0.79 0.0 0.79 0.0 0.87 0.0 0.0284 -20.1054 0.81 0.0 0.78 0.0 0.75 0.0
Guyana 328 0.91 0.0 0.0137 28.6859 0.67 0.0 0.91 0.0 0.69 0.0 0.92 0.0 0.0156 26.7895 0.68 0.0 0.92 0.0 0.69 0.0 0.9 0.0 0.0119 30.4176 0.66 0.0 0.9 0.0 0.69 0.0
Haiti 332 0.4 0.0 0.0205 14.2489 -0.17 0.2 0.33 0.01 0.81 0.0 0.43 0.0 0.0233 10.6592 -0.12 0.35 0.34 0.01 0.81 0.0 0.37 0.0 0.018 17.2389 -0.22 0.1 0.32 0.01 0.8 0.0
Honduras 340 0.95 0.0 0.0276 0.3684 0.9 0.0 0.82 0.0 0.95 0.0 0.95 0.0 0.0286 0.1797 0.89 0.0 0.82 0.0 0.95 0.0 0.95 0.0 0.0268 0.3398 0.9 0.0 0.82 0.0 0.95 0.0
China (Hong Kong Special Administrative Region) 344 0.92 0.0 0.0228 7.9191 -0.72 0.0 0.94 0.0 0.9 0.0 0.91 0.0 0.0213 15.4528 -0.73 0.0 0.95 0.0 0.9 0.0 0.93 0.0 0.0253 -2.9891 -0.72 0.0 0.93 0.0 0.92 0.0
Hungary 348 -0.19 0.14 -0.003 80.8133 -0.72 0.0 -0.61 0.0 0.67 0.0 -0.17 0.2 -0.0028 83.6951 -0.83 0.0 -0.59 0.0 0.81 0.0 -0.2 0.13 -0.003 77.2257 -0.56 0.0 -0.58 0.0 0.49 0.0
Iceland 352 0.75 0.0 0.0127 37.1441 0.29 0.02 0.69 0.0 0.71 0.0 0.72 0.0 0.0105 46.8122 0.25 0.06 0.68 0.0 0.7 0.0 0.76 0.0 0.0147 28.6378 0.32 0.01 0.69 0.0 0.72 0.0
India 356 0.94 0.0 0.0398 -30.5466 0.87 0.0 0.88 0.0 0.97 0.0 0.94 0.0 0.0439 -39.2947 0.87 0.0 0.88 0.0 0.97 0.0 0.94 0.0 0.0359 -22.3939 0.86 0.0 0.88 0.0 0.97 0.0
Indonesia 360 0.94 0.0 0.021 11.7501 0.93 0.0 0.94 0.0 0.91 0.0 0.95 0.0 0.0209 13.7564 0.93 0.0 0.95 0.0 0.91 0.0 0.94 0.0 0.021 10.0262 0.92 0.0 0.94 0.0 0.9 0.0
Iran (Islamic Republic of) 364 0.95 0.0 0.0219 3.5698 0.89 0.0 0.97 0.0 0.98 0.0 0.97 0.0 0.0248 -2.2539 0.91 0.0 0.98 0.0 0.98 0.0 0.93 0.0 0.0193 8.9416 0.87 0.0 0.95 0.0 0.97 0.0
Iraq 368 0.01 0.95 0.0001 63.0116 -0.12 0.36 -0.21 0.11 0.37 0.0 0.34 0.01 0.0032 59.3947 0.22 0.09 0.11 0.4 0.59 0.0 -0.19 0.16 -0.0023 65.1508 -0.31 0.02 -0.38 0.0 0.22 0.1
Ireland 372 0.75 0.0 0.0255 -15.4438 0.62 0.0 0.51 0.0 0.53 0.0 0.77 0.0 0.0251 -11.6432 0.59 0.0 0.56 0.0 0.57 0.0 0.73 0.0 0.0253 -17.2016 0.64 0.0 0.47 0.0 0.49 0.0
Israel 376 0.88 0.0 0.0147 27.5277 -0.22 0.1 0.94 0.0 0.94 0.0 0.89 0.0 0.0151 28.0448 -0.19 0.15 0.95 0.0 0.95 0.0 0.85 0.0 0.0139 28.1964 -0.25 0.06 0.93 0.0 0.93 0.0
Italy 380 0.7 0.0 0.0181 14.0101 -0.83 0.0 0.78 0.0 0.9 0.0 0.73 0.0 0.0181 16.6697 -0.84 0.0 0.82 0.0 0.93 0.0 0.66 0.0 0.0177 12.1903 -0.82 0.0 0.74 0.0 0.87 0.0
Ivory Coast 384 0.69 0.0 0.0269 -21.6589 0.45 0.0 0.16 0.23 0.75 0.0 0.68 0.0 0.0266 -19.1276 0.44 0.0 0.15 0.25 0.75 0.0 0.69 0.0 0.0274 -24.3983 0.46 0.0 0.16 0.21 0.74 0.0
Jamaica 388 0.82 0.0 0.0095 45.2593 0.68 0.0 0.74 0.0 0.81 0.0 0.86 0.0 0.0102 45.1755 0.68 0.0 0.82 0.0 0.88 0.0 0.75 0.0 0.0091 44.6581 0.65 0.0 0.64 0.0 0.71 0.0
Japan 392 0.4 0.0 0.0173 29.8544 -0.94 0.0 0.64 0.0 0.96 0.0 0.4 0.0 0.0183 29.9234 -0.94 0.0 0.64 0.0 0.96 0.0 0.39 0.0 0.0157 31.303 -0.94 0.0 0.63 0.0 0.96 0.0
Kazakhstan 398 0.89 0.0 0.0148 21.6211 -0.76 0.0 0.87 0.0 0.9 0.0 0.88 0.0 0.0108 38.7286 -0.78 0.0 0.85 0.0 0.9 0.0 0.89 0.0 0.0176 8.1821 -0.74 0.0 0.88 0.0 0.89 0.0
Jordan 400 0.88 0.0 0.0157 27.0745 0.68 0.0 0.86 0.0 0.93 0.0 0.88 0.0 0.017 24.987 0.68 0.0 0.86 0.0 0.93 0.0 0.88 0.0 0.0145 28.9163 0.68 0.0 0.86 0.0 0.92 0.0
Kenya 404 -0.15 0.27 -0.0044 66.6691 -0.27 0.04 -0.43 0.0 0.59 0.0 -0.13 0.32 -0.0042 67.9313 -0.25 0.05 -0.41 0.0 0.57 0.0 -0.14 0.27 -0.0041 64.3613 -0.27 0.04 -0.44 0.0 0.6 0.0
Democratic People's Republic of Korea 408 0.47 0.0 0.0249 12.7991 0.14 0.29 -0.12 0.35 0.77 0.0 0.5 0.0 0.0287 7.7165 0.16 0.22 -0.12 0.36 0.8 0.0 0.4 0.0 0.0193 21.098 0.1 0.44 -0.16 0.23 0.7 0.0
Republic of Korea 410 0.84 0.0 0.0225 3.7533 -0.36 0.01 0.9 0.0 0.98 0.0 0.87 0.0 0.0228 6.8255 -0.29 0.03 0.92 0.0 0.96 0.0 0.81 0.0 0.0218 1.9354 -0.41 0.0 0.88 0.0 0.99 0.0
Kuwait 414 0.75 0.0 0.0101 42.2295 0.74 0.0 0.69 0.0 0.75 0.0 0.73 0.0 0.01 44.9015 0.72 0.0 0.67 0.0 0.72 0.0 0.76 0.0 0.0103 40.0654 0.75 0.0 0.7 0.0 0.76 0.0
Kyrgyzstan 417 0.72 0.0 0.0126 33.9423 0.5 0.01 0.49 0.01 0.73 0.0 0.73 0.0 0.0123 38.7411 0.51 0.01 0.5 0.01 0.72 0.0 0.72 0.0 0.0129 29.2523 0.5 0.01 0.48 0.01 0.73 0.0
Lao People's Democratic Republic 418 0.79 0.0 0.0274 -4.4448 0.72 0.0 0.8 0.0 0.89 0.0 0.81 0.0 0.0285 -4.9305 0.73 0.0 0.82 0.0 0.9 0.0 0.77 0.0 0.0266 -4.2821 0.7 0.0 0.78 0.0 0.87 0.0
Lebanon 422 0.48 0.0 0.0132 30.2172 0.42 0.0 0.34 0.01 0.52 0.0 0.53 0.0 0.0122 36.2429 0.47 0.0 0.38 0.0 0.59 0.0 0.43 0.0 0.0135 26.4689 0.38 0.0 0.3 0.02 0.47 0.0
Lesotho 426 -0.3 0.02 -0.0077 69.7432 -0.37 0.0 -0.34 0.01 0.16 0.24 -0.31 0.02 -0.0093 77.0922 -0.36 0.0 -0.34 0.01 0.1 0.43 -0.21 0.11 -0.0048 59.6363 -0.32 0.01 -0.29 0.03 0.26 0.04
Latvia 428 0.39 0.04 0.0076 47.8368 -0.65 0.0 0.17 0.38 0.84 0.0 0.44 0.02 0.0063 57.3407 -0.62 0.0 0.22 0.27 0.86 0.0 0.38 0.04 0.0088 38.5436 -0.65 0.0 0.16 0.4 0.83 0.0
Liberia 430 -0.28 0.03 -0.0127 76.5524 -0.49 0.0 -0.39 0.0 0.62 0.0 -0.31 0.02 -0.0138 80.8012 -0.53 0.0 -0.43 0.0 0.63 0.0 -0.25 0.06 -0.0117 72.5247 -0.46 0.0 -0.36 0.0 0.6 0.0
Libya 434 0.22 0.68 0.0131 31.2859 -0.85 0.03 -0.07 0.89 0.85 0.03 0.38 0.46 0.01 44.3418 -0.88 0.02 0.07 0.9 0.88 0.02 0.16 0.76 0.0136 26.5251 -0.84 0.04 -0.11 0.83 0.84 0.04
Lithuania 440 0.74 0.0 0.0069 49.9292 0.37 0.05 0.79 0.0 0.76 0.0 0.8 0.0 0.0058 58.9555 0.41 0.03 0.85 0.0 0.83 0.0 0.7 0.0 0.0077 41.8649 0.34 0.08 0.75 0.0 0.73 0.0
Luxembourg 442 0.09 0.72 0.0055 61.0947 0.57 0.01 0.62 0.0 -0.74 0.0 0.02 0.94 0.0009 79.6301 0.56 0.01 0.56 0.01 -0.74 0.0 0.12 0.61 0.0094 44.7219 0.56 0.01 0.65 0.0 -0.73 0.0
China (Macao Special Administrative Region) 446 0.71 0.0 0.0112 47.0054 -0.11 0.42 0.85 0.0 0.93 0.0 0.7 0.0 0.012 47.2766 -0.11 0.39 0.84 0.0 0.93 0.0 0.71 0.0 0.0104 46.7004 -0.11 0.41 0.85 0.0 0.93 0.0
Madagascar 450 -0.88 0.0 -0.0259 111.8231 -0.82 0.0 -0.92 0.0 -0.94 0.0 -0.88 0.0 -0.0272 115.9779 -0.82 0.0 -0.92 0.0 -0.94 0.0 -0.88 0.0 -0.0246 107.6779 -0.82 0.0 -0.92 0.0 -0.94 0.0
Malawi 454 0.52 0.0 0.022 -2.9518 0.67 0.0 0.04 0.74 0.26 0.05 0.52 0.0 0.023 -3.0879 0.66 0.0 0.04 0.76 0.26 0.04 0.53 0.0 0.021 -2.7386 0.68 0.0 0.05 0.73 0.25 0.05
Malaysia 458 0.92 0.0 0.0299 -11.6723 -0.36 0.01 0.94 0.0 0.94 0.0 0.92 0.0 0.0323 -16.0573 -0.36 0.0 0.94 0.0 0.94 0.0 0.91 0.0 0.0276 -7.3865 -0.36 0.01 0.93 0.0 0.94 0.0
Maldives 462 0.9 0.0 0.0351 -15.1902 0.74 0.0 0.88 0.0 0.86 0.0 0.9 0.0 0.0359 -16.3824 0.74 0.0 0.88 0.0 0.86 0.0 0.9 0.0 0.0344 -14.3154 0.74 0.0 0.88 0.0 0.86 0.0
Mali 466 0.95 0.0 0.0203 -0.0289 0.94 0.0 0.94 0.0 0.86 0.0 0.95 0.0 0.0203 0.6471 0.94 0.0 0.94 0.0 0.86 0.0 0.95 0.0 0.0202 -0.648 0.94 0.0 0.94 0.0 0.85 0.0
Malta 470 0.83 0.0 0.0253 -5.7838 0.38 0.0 0.87 0.0 0.8 0.0 0.84 0.0 0.0269 -9.0227 0.38 0.0 0.88 0.0 0.81 0.0 0.82 0.0 0.0235 -2.2172 0.36 0.0 0.85 0.0 0.79 0.0
Mauritania 478 0.89 0.0 0.0164 17.4741 0.9 0.0 0.08 0.53 0.83 0.0 0.88 0.0 0.0169 17.7076 0.89 0.0 0.06 0.66 0.82 0.0 0.91 0.0 0.0158 17.2904 0.92 0.0 0.11 0.39 0.84 0.0
Mauritius 480 0.98 0.0 0.0208 10.74 0.8 0.0 0.96 0.0 0.98 0.0 0.97 0.0 0.0211 13.6718 0.81 0.0 0.96 0.0 0.97 0.0 0.98 0.0 0.02 9.7821 0.79 0.0 0.97 0.0 0.98 0.0
Mexico 484 0.91 0.0 0.0203 9.5373 0.71 0.0 0.93 0.0 0.93 0.0 0.93 0.0 0.0218 8.1619 0.75 0.0 0.94 0.0 0.94 0.0 0.88 0.0 0.0188 11.1149 0.66 0.0 0.92 0.0 0.92 0.0
Mongolia 496 0.61 0.0 0.0186 17.1791 0.52 0.0 0.26 0.05 0.47 0.0 0.61 0.0 0.0212 14.265 0.53 0.0 0.25 0.06 0.46 0.0 0.61 0.0 0.0162 19.7836 0.52 0.0 0.27 0.04 0.47 0.0
Republic of Moldova 498 0.91 0.0 0.0159 26.4222 -0.3 0.12 0.71 0.0 0.82 0.0 0.9 0.0 0.019 22.4643 -0.36 0.06 0.69 0.0 0.84 0.0 0.91 0.0 0.0135 28.5831 -0.23 0.24 0.72 0.0 0.78 0.0
Montenegro 499 0.55 0.04 0.0079 48.7863 -0.64 0.01 0.74 0.0 0.93 0.0 0.61 0.02 0.0098 44.9644 -0.61 0.02 0.77 0.0 0.94 0.0 0.47 0.09 0.0064 51.2901 -0.66 0.01 0.68 0.01 0.89 0.0
Morocco 504 0.98 0.0 0.0221 -2.7864 0.98 0.0 0.98 0.0 0.97 0.0 0.98 0.0 0.0229 -3.6319 0.98 0.0 0.98 0.0 0.97 0.0 0.98 0.0 0.0213 -2.0946 0.98 0.0 0.98 0.0 0.97 0.0
Mozambique 508 0.73 0.0 0.0287 -8.0053 0.47 0.0 0.89 0.0 0.74 0.0 0.71 0.0 0.0282 -5.2706 0.43 0.0 0.88 0.0 0.76 0.0 0.75 0.0 0.0288 -10.0882 0.5 0.0 0.88 0.0 0.71 0.0
Oman 512 0.9 0.0 0.0085 51.365 0.9 0.0 0.9 0.0 0.71 0.0 0.9 0.0 0.0073 57.0788 0.9 0.0 0.91 0.0 0.69 0.0 0.89 0.0 0.0091 47.8086 0.89 0.0 0.89 0.0 0.71 0.0

Malta 470 0.83 0.0 0.0253 -5.7838 0.38 0.0 0.87 0.0 0.8 0.0 0.84 0.0 0.0269 -9.0227 0.38 0.0 0.88 0.0 0.81 0.0 0.82 0.0 0.0235 -2.2172 0.36 0.0 0.85 0.0 0.79 0.0
Mauritania 478 0.89 0.0 0.0164 17.4741 0.9 0.0 0.08 0.53 0.83 0.0 0.88 0.0 0.0169 17.7076 0.89 0.0 0.06 0.66 0.82 0.0 0.91 0.0 0.0158 17.2904 0.92 0.0 0.11 0.39 0.84 0.0
Mauritius 480 0.98 0.0 0.0208 10.74 0.8 0.0 0.96 0.0 0.98 0.0 0.97 0.0 0.0211 13.6718 0.81 0.0 0.96 0.0 0.97 0.0 0.98 0.0 0.02 9.7821 0.79 0.0 0.97 0.0 0.98 0.0
Mexico 484 0.91 0.0 0.0203 9.5373 0.71 0.0 0.93 0.0 0.93 0.0 0.93 0.0 0.0218 8.1619 0.75 0.0 0.94 0.0 0.94 0.0 0.88 0.0 0.0188 11.1149 0.66 0.0 0.92 0.0 0.92 0.0
Mongolia 496 0.61 0.0 0.0186 17.1791 0.52 0.0 0.26 0.05 0.47 0.0 0.61 0.0 0.0212 14.265 0.53 0.0 0.25 0.06 0.46 0.0 0.61 0.0 0.0162 19.7836 0.52 0.0 0.27 0.04 0.47 0.0
Republic of Moldova 498 0.91 0.0 0.0159 26.4222 -0.3 0.12 0.71 0.0 0.82 0.0 0.9 0.0 0.019 22.4643 -0.36 0.06 0.69 0.0 0.84 0.0 0.91 0.0 0.0135 28.5831 -0.23 0.24 0.72 0.0 0.78 0.0
Montenegro 499 0.55 0.04 0.0079 48.7863 -0.64 0.01 0.74 0.0 0.93 0.0 0.61 0.02 0.0098 44.9644 -0.61 0.02 0.77 0.0 0.94 0.0 0.47 0.09 0.0064 51.2901 -0.66 0.01 0.68 0.01 0.89 0.0
Morocco 504 0.98 0.0 0.0221 -2.7864 0.98 0.0 0.98 0.0 0.97 0.0 0.98 0.0 0.0229 -3.6319 0.98 0.0 0.98 0.0 0.97 0.0 0.98 0.0 0.0213 -2.0946 0.98 0.0 0.98 0.0 0.97 0.0
Mozambique 508 0.73 0.0 0.0287 -8.0053 0.47 0.0 0.89 0.0 0.74 0.0 0.71 0.0 0.0282 -5.2706 0.43 0.0 0.88 0.0 0.76 0.0 0.75 0.0 0.0288 -10.0882 0.5 0.0 0.88 0.0 0.71 0.0
Oman 512 0.9 0.0 0.0085 51.365 0.9 0.0 0.9 0.0 0.71 0.0 0.9 0.0 0.0073 57.0788 0.9 0.0 0.91 0.0 0.69 0.0 0.89 0.0 0.0091 47.8086 0.89 0.0 0.89 0.0 0.71 0.0
Namibia 516 -0.05 0.69 -0.0018 60.243 0.37 0.0 -0.43 0.0 -0.35 0.01 -0.03 0.8 -0.0014 62.161 0.4 0.0 -0.39 0.0 -0.37 0.0 -0.07 0.59 -0.0022 58.083 0.31 0.02 -0.46 0.0 -0.32 0.01
Nepal 524 0.94 0.0 0.0259 -0.7519 0.95 0.0 0.93 0.0 0.91 0.0 0.94 0.0 0.0277 -3.9673 0.95 0.0 0.93 0.0 0.91 0.0 0.94 0.0 0.0242 2.218 0.95 0.0 0.93 0.0 0.9 0.0
Netherlands 528 0.74 0.0 0.0183 19.224 0.69 0.0 0.88 0.0 0.22 0.1 0.76 0.0 0.0162 28.4384 0.66 0.0 0.9 0.0 0.27 0.04 0.7 0.0 0.0196 12.3326 0.7 0.0 0.85 0.0 0.16 0.22
Netherlands Antilles (former) 530 -0.2 0.17 -0.0017 76.6435 0.18 0.21 -0.0 0.99 -0.49 0.0 -0.18 0.21 -0.0016 78.9991 0.2 0.15 0.0 0.98 -0.49 0.0 -0.21 0.14 -0.0018 74.2025 0.15 0.29 -0.01 0.97 -0.49 0.0
New Caledonia 540 -0.48 0.0 -0.0255 142.4328 -0.85 0.0 0.62 0.0 0.81 0.0 -0.48 0.0 -0.0268 149.9 -0.85 0.0 0.61 0.0 0.81 0.0 -0.47 0.0 -0.0238 134.4089 -0.85 0.0 0.62 0.0 0.81 0.0
Vanuatu 548 0.61 0.0 0.034 -26.0415 0.44 0.0 0.06 0.65 0.66 0.0 0.6 0.0 0.0361 -29.3659 0.43 0.0 0.03 0.81 0.66 0.0 0.62 0.0 0.0318 -22.0974 0.45 0.0 0.08 0.55 0.65 0.0
New Zealand 554 0.66 0.0 0.0299 -17.1491 0.86 0.0 -0.48 0.0 -0.21 0.1 0.69 0.0 0.0268 -4.7862 0.87 0.0 -0.47 0.0 -0.18 0.17 0.64 0.0 0.032 -26.2848 0.86 0.0 -0.49 0.0 -0.24 0.07
Nicaragua 558 0.71 0.0 0.0237 10.3541 0.59 0.0 0.21 0.11 0.91 0.0 0.7 0.0 0.0239 12.9993 0.59 0.0 0.17 0.19 0.89 0.0 0.71 0.0 0.0233 8.2637 0.58 0.0 0.24 0.07 0.91 0.0
Niger 562 0.89 0.0 0.0306 -21.5639 0.79 0.0 0.89 0.0 0.94 0.0 0.89 0.0 0.0309 -21.7546 0.79 0.0 0.89 0.0 0.93 0.0 0.89 0.0 0.0304 -21.655 0.8 0.0 0.89 0.0 0.94 0.0
Nigeria 566 0.71 0.0 0.0081 27.7992 0.74 0.0 0.73 0.0 0.41 0.0 0.71 0.0 0.0077 29.5556 0.75 0.0 0.73 0.0 0.42 0.0 0.7 0.0 0.0084 26.0841 0.73 0.0 0.73 0.0 0.4 0.0
Norway 578 0.89 0.0 0.013 35.3256 0.83 0.0 0.95 0.0 0.66 0.0 0.92 0.0 0.0117 42.2607 0.83 0.0 0.96 0.0 0.73 0.0 0.85 0.0 0.0139 29.5981 0.82 0.0 0.92 0.0 0.61 0.0
Pakistan 586 0.82 0.0 0.0325 -15.8542 -0.28 0.03 0.65 0.0 0.94 0.0 0.82 0.0 0.039 -29.7825 -0.27 0.04 0.65 0.0 0.93 0.0 0.81 0.0 0.0268 -3.4238 -0.28 0.03 0.64 0.0 0.93 0.0
Panama 591 0.72 0.0 0.0148 36.379 0.33 0.01 0.85 0.0 0.89 0.0 0.7 0.0 0.0161 35.9912 0.29 0.02 0.83 0.0 0.89 0.0 0.74 0.0 0.0134 37.1431 0.37 0.0 0.87 0.0 0.89 0.0
Papua New Guinea 598 0.74 0.09 0.0329 -8.4318 0.94 0.01 -0.56 0.25 -0.89 0.02 0.67 0.14 0.0369 -14.4402 0.85 0.03 -0.42 0.41 -0.82 0.04 0.78 0.07 0.0284 -0.7926 0.98 0.0 -0.68 0.13 -0.92 0.01
Paraguay 600 0.82 0.0 0.0223 11.123 -0.13 0.32 0.2 0.13 0.93 0.0 0.81 0.0 0.0243 8.3227 -0.18 0.18 0.2 0.12 0.94 0.0 0.83 0.0 0.0207 12.9597 -0.09 0.52 0.2 0.12 0.91 0.0
Peru 604 0.79 0.0 0.0276 1.4998 0.66 0.0 0.8 0.0 0.75 0.0 0.77 0.0 0.0278 3.0248 0.62 0.0 0.78 0.0 0.76 0.0 0.81 0.0 0.0272 0.1972 0.69 0.0 0.83 0.0 0.74 0.0
Philippines 608 0.94 0.0 0.0136 35.6603 0.89 0.0 0.95 0.0 0.94 0.0 0.94 0.0 0.0135 37.594 0.89 0.0 0.95 0.0 0.94 0.0 0.94 0.0 0.0134 34.3501 0.88 0.0 0.94 0.0 0.94 0.0
Poland 616 0.16 0.22 0.0057 53.0656 -0.61 0.0 -0.13 0.34 0.68 0.0 0.16 0.22 0.0061 55.5289 -0.68 0.0 -0.11 0.39 0.74 0.0 0.16 0.23 0.0053 50.4938 -0.53 0.0 -0.14 0.31 0.62 0.0
Portugal 620 0.85 0.0 0.0143 28.0886 -0.23 0.09 0.91 0.0 0.96 0.0 0.86 0.0 0.0145 30.7025 -0.2 0.12 0.91 0.0 0.96 0.0 0.84 0.0 0.0141 25.3621 -0.24 0.06 0.91 0.0 0.95 0.0
Guinea-Bissau 624 0.8 0.0 0.0204 5.2082 0.76 0.0 0.71 0.0 0.77 0.0 0.77 0.0 0.0183 12.1376 0.73 0.0 0.67 0.0 0.75 0.0 0.82 0.0 0.022 -0.3945 0.78 0.0 0.74 0.0 0.78 0.0
Timor-Leste 626 0.51 0.0 0.0414 -35.4292 0.31 0.02 -0.73 0.0 0.84 0.0 0.62 0.0 0.0453 -39.9513 0.43 0.0 -0.71 0.0 0.82 0.0 0.46 0.0 0.0393 -33.6736 0.25 0.06 -0.73 0.0 0.84 0.0
Romania 642 0.85 0.0 0.0108 36.345 0.19 0.16 0.84 0.0 0.88 0.0 0.82 0.0 0.0124 34.2438 0.09 0.49 0.84 0.0 0.9 0.0 0.85 0.0 0.0092 38.232 0.29 0.02 0.8 0.0 0.82 0.0
Russian Federation 643 0.84 0.0 0.0126 28.6282 0.51 0.01 0.91 0.0 0.94 0.0 0.87 0.0 0.0098 43.5208 0.55 0.0 0.92 0.0 0.96 0.0 0.83 0.0 0.0141 17.93 0.49 0.01 0.9 0.0 0.93 0.0
Rwanda 646 0.38 0.0 0.0178 13.5045 0.2 0.13 0.46 0.0 0.62 0.0 0.36 0.01 0.0172 15.9629 0.17 0.19 0.44 0.0 0.65 0.0 0.4 0.0 0.0182 11.3481 0.23 0.08 0.48 0.0 0.59 0.0
Saint Kitts and Nevis 659 0.82 0.0 0.0153 30.1121 0.45 0.0 0.93 0.0 0.84 0.0 0.82 0.0 0.0172 28.3933 0.44 0.0 0.93 0.0 0.85 0.0 0.81 0.0 0.0141 30.0566 0.45 0.0 0.92 0.0 0.82 0.0
Saint Lucia 662 0.94 0.0 0.0117 41.3603 0.82 0.0 0.93 0.0 0.92 0.0 0.93 0.0 0.0131 40.4791 0.8 0.0 0.93 0.0 0.93 0.0 0.94 0.0 0.0107 41.2153 0.84 0.0 0.93 0.0 0.91 0.0
Saint Vincent and the Grenadines 670 0.85 0.0 0.0101 45.8403 0.8 0.0 0.8 0.0 0.86 0.0 0.87 0.0 0.011 45.9607 0.8 0.0 0.83 0.0 0.89 0.0 0.84 0.0 0.0102 43.293 0.79 0.0 0.78 0.0 0.84 0.0
Sao Tome and Principe 678 0.4 0.0 0.0121 33.2215 0.38 0.0 0.41 0.0 0.12 0.37 0.41 0.0 0.0133 32.5909 0.4 0.0 0.43 0.0 0.12 0.37 0.38 0.0 0.011 33.6426 0.36 0.0 0.4 0.0 0.12 0.36
Saudi Arabia 682 0.95 0.0 0.0168 21.6797 0.91 0.0 0.95 0.0 0.95 0.0 0.95 0.0 0.0169 23.1684 0.91 0.0 0.95 0.0 0.95 0.0 0.95 0.0 0.017 19.9416 0.91 0.0 0.95 0.0 0.95 0.0
Senegal 686 0.2 0.13 0.012 25.987 -0.23 0.08 -0.47 0.0 0.74 0.0 0.19 0.15 0.0123 26.757 -0.23 0.07 -0.45 0.0 0.73 0.0 0.21 0.12 0.0115 25.8669 -0.22 0.09 -0.49 0.0 0.75 0.0
Serbia 688 0.8 0.0 0.0181 25.0634 0.73 0.0 0.9 0.0 0.36 0.21 0.79 0.0 0.0182 27.7351 0.73 0.0 0.91 0.0 0.35 0.22 0.8 0.0 0.0174 24.0853 0.72 0.0 0.9 0.0 0.37 0.19
Seychelles 690 0.77 0.07 0.0019 67.918 0.94 0.01 0.65 0.16 -0.17 0.74 0.34 0.51 0.0007 76.2863 0.89 0.02 0.15 0.78 -0.65 0.16 0.91 0.01 0.0033 59.7762 0.83 0.04 0.85 0.03 0.12 0.81
Sierra Leone 694 0.53 0.0 0.0254 -9.1689 0.72 0.0 0.63 0.0 -0.64 0.0 0.54 0.0 0.0251 -7.2956 0.73 0.0 0.63 0.0 -0.65 0.0 0.52 0.0 0.0257 -10.9366 0.71 0.0 0.64 0.0 -0.64 0.0
Slovakia 703 0.05 0.79 0.0015 70.379 -0.7 0.0 -0.76 0.0 0.84 0.0 0.05 0.82 0.0011 75.3709 -0.7 0.0 -0.76 0.0 0.83 0.0 0.06 0.77 0.0019 65.4066 -0.71 0.0 -0.75 0.0 0.85 0.0
Viet Nam 704 0.68 0.0 0.0125 39.9828 0.56 0.0 0.64 0.0 0.73 0.0 0.71 0.0 0.0123 45.2814 0.59 0.0 0.67 0.0 0.76 0.0 0.65 0.0 0.0125 35.4574 0.54 0.0 0.62 0.0 0.7 0.0
Slovenia 705 0.85 0.0 0.0148 32.5547 0.86 0.0 0.4 0.03 0.7 0.0 0.87 0.0 0.0124 43.0948 0.86 0.0 0.43 0.02 0.73 0.0 0.83 0.0 0.0173 21.3569 0.85 0.0 0.38 0.05 0.68 0.0
South Africa 710 0.3 0.02 0.0143 18.2138 -0.1 0.45 0.27 0.04 0.32 0.01 0.25 0.06 0.0131 24.6171 -0.05 0.69 0.21 0.11 0.24 0.07 0.31 0.02 0.013 19.168 -0.11 0.42 0.28 0.03 0.33 0.01
Zimbabwe 716 0.12 0.35 0.0051 43.9266 0.18 0.18 0.19 0.14 -0.19 0.15 0.12 0.38 0.0052 45.686 0.18 0.18 0.19 0.15 -0.2 0.12 0.13 0.32 0.0051 41.7473 0.18 0.17 0.2 0.13 -0.18 0.18
Spain 724 0.83 0.0 0.015 30.5519 -0.86 0.0 0.89 0.0 0.92 0.0 0.87 0.0 0.0161 30.1656 -0.86 0.0 0.92 0.0 0.95 0.0 0.8 0.0 0.014 30.4438 -0.86 0.0 0.85 0.0 0.89 0.0
Sudan 729 0.73 0.04 0.005 52.2475 0.72 0.04 0.83 0.01 -0.42 0.3 0.79 0.02 0.0046 55.9161 0.78 0.02 0.89 0.0 -0.44 0.27 0.68 0.06 0.0052 49.0578 0.68 0.07 0.78 0.02 -0.4 0.32

Sudan (former) 736 0.78 0.0 0.0259 -4.2826 0.7 0.0 0.76 0.0 0.71 0.0 0.84 0.0 0.0265 -2.7881 0.78 0.0 0.84 0.0 0.71 0.0 0.72 0.0 0.0252 -5.1998 0.63 0.0 0.69 0.0 0.71 0.0
Suriname 740 0.92 0.0 0.0162 24.7562 0.65 0.0 0.57 0.0 0.93 0.0 0.93 0.0 0.0175 24.548 0.66 0.0 0.58 0.0 0.93 0.0 0.91 0.0 0.0147 25.5755 0.63 0.0 0.56 0.0 0.93 0.0
Eswatini 748 0.44 0.0 0.0246 -4.4562 0.63 0.0 -0.38 0.0 -0.08 0.56 0.45 0.0 0.0262 -6.1048 0.62 0.0 -0.4 0.0 -0.03 0.82 0.43 0.0 0.0233 -3.4151 0.64 0.0 -0.35 0.01 -0.12 0.37
Sweden 752 0.95 0.0 0.0235 7.0179 0.78 0.0 0.95 0.0 0.83 0.0 0.95 0.0 0.0214 15.5861 0.78 0.0 0.96 0.0 0.83 0.0 0.93 0.0 0.0249 0.2113 0.76 0.0 0.93 0.0 0.83 0.0
Switzerland 756 -0.27 0.04 -0.0159 132.0578 -0.69 0.0 0.37 0.0 0.64 0.0 -0.29 0.03 -0.0154 133.2048 -0.74 0.0 0.43 0.0 0.67 0.0 -0.25 0.05 -0.0162 130.068 -0.64 0.0 0.32 0.01 0.6 0.0
Syrian Arab Republic 760 -0.89 0.02 -0.0334 162.0173 -0.86 0.03 -0.44 0.39 -0.93 0.01 -0.93 0.01 -0.0309 160.1846 -0.9 0.01 -0.57 0.24 -0.89 0.02 -0.84 0.04 -0.0346 160.8474 -0.8 0.05 -0.34 0.51 -0.92 0.01
Tajikistan 762 0.63 0.0 0.016 31.1512 0.59 0.0 0.56 0.0 0.57 0.0 0.74 0.0 0.0145 37.5512 0.67 0.0 0.67 0.0 0.72 0.0 0.56 0.0 0.0175 25.271 0.55 0.0 0.49 0.01 0.5 0.01
Thailand 764 0.8 0.0 0.0229 12.8922 0.59 0.0 0.81 0.0 0.92 0.0 0.8 0.0 0.0246 12.6661 0.59 0.0 0.81 0.0 0.92 0.0 0.81 0.0 0.0214 13.047 0.6 0.0 0.81 0.0 0.92 0.0
Togo 768 0.38 0.0 0.01 31.303 0.06 0.66 0.63 0.0 0.72 0.0 0.31 0.02 0.0077 37.1426 -0.01 0.91 0.58 0.0 0.68 0.0 0.44 0.0 0.0122 25.5658 0.12 0.36 0.67 0.0 0.75 0.0
Trinidad and Tobago 780 0.76 0.0 0.0116 37.2278 0.37 0.0 0.66 0.0 0.89 0.0 0.76 0.0 0.0132 35.4027 0.36 0.0 0.66 0.0 0.89 0.0 0.76 0.0 0.0098 39.3157 0.37 0.0 0.65 0.0 0.89 0.0
United Arab Emirates 784 0.62 0.0 0.022 0.3965 0.45 0.0 0.5 0.0 0.31 0.02 0.64 0.0 0.0217 3.8703 0.45 0.0 0.52 0.0 0.33 0.01 0.62 0.0 0.0224 -2.6547 0.45 0.0 0.51 0.0 0.31 0.02
Tunisia 788 0.98 0.0 0.0251 -8.5782 0.97 0.0 0.97 0.0 0.94 0.0 0.98 0.0 0.0269 -11.6749 0.97 0.0 0.97 0.0 0.94 0.0 0.98 0.0 0.0233 -5.5653 0.97 0.0 0.96 0.0 0.94 0.0
Turkiye 792 0.91 0.0 0.0276 -29.5479 0.49 0.0 0.84 0.0 0.94 0.0 0.92 0.0 0.0279 -27.3445 0.51 0.0 0.85 0.0 0.94 0.0 0.9 0.0 0.0268 -29.9508 0.47 0.0 0.83 0.0 0.95 0.0
Turkmenistan 795 0.94 0.0 0.0132 30.0788 0.73 0.0 0.91 0.0 0.85 0.0 0.94 0.0 0.0125 35.6592 0.76 0.0 0.92 0.0 0.83 0.0 0.93 0.0 0.0139 24.7673 0.72 0.0 0.91 0.0 0.86 0.0
Uganda 800 -0.36 0.01 -0.0197 93.9889 -0.8 0.0 -0.17 0.19 0.85 0.0 -0.4 0.0 -0.0199 97.2551 -0.81 0.0 -0.17 0.21 0.8 0.0 -0.32 0.01 -0.0189 89.7371 -0.78 0.0 -0.16 0.21 0.87 0.0
Ukraine 804 0.21 0.29 0.0034 59.5137 -0.01 0.95 0.4 0.03 0.36 0.06 0.19 0.34 0.0027 66.8054 -0.02 0.9 0.39 0.04 0.34 0.07 0.22 0.26 0.0038 53.0016 -0.0 0.98 0.41 0.03 0.38 0.05
North Macedonia 807 0.84 0.0 0.0076 52.6758 0.36 0.06 0.9 0.0 0.81 0.0 0.83 0.0 0.0068 57.1668 0.35 0.07 0.89 0.0 0.8 0.0 0.85 0.0 0.008 49.2567 0.38 0.05 0.91 0.0 0.81 0.0
USSR 810 -0.16 0.38 -0.001 70.5767 -0.56 0.0 0.14 0.47 0.22 0.24 0.28 0.13 0.0019 65.0319 -0.77 0.0 0.64 0.0 0.76 0.0 -0.32 0.08 -0.0027 71.208 -0.42 0.02 -0.07 0.69 -0.01 0.94
Egypt 818 0.98 0.0 0.017 10.6767 0.98 0.0 0.98 0.0 0.72 0.0 0.97 0.0 0.0173 11.979 0.98 0.0 0.99 0.0 0.72 0.0 0.98 0.0 0.0167 9.4162 0.98 0.0 0.98 0.0 0.72 0.0
United Kingdom of Great Britain and Northern Ireland 826 0.8 0.0 0.0254 -7.407 0.76 0.0 0.89 0.0 0.38 0.0 0.79 0.0 0.0218 7.2192 0.74 0.0 0.88 0.0 0.37 0.0 0.81 0.0 0.0291 -22.1562 0.77 0.0 0.9 0.0 0.38 0.0
United Republic of Tanzania 834 0.75 0.0 0.0226 5.7094 0.43 0.0 0.8 0.0 0.97 0.0 0.77 0.0 0.0236 5.3467 0.46 0.0 0.81 0.0 0.97 0.0 0.73 0.0 0.0217 5.8538 0.41 0.0 0.79 0.0 0.97 0.0
United States of America 840 0.96 0.0 0.009 44.3751 0.84 0.0 0.9 0.0 0.97 0.0 0.95 0.0 0.0074 52.9551 0.84 0.0 0.88 0.0 0.95 0.0 0.96 0.0 0.0102 36.8308 0.83 0.0 0.9 0.0 0.97 0.0
Burkina Faso 854 0.92 0.0 0.013 21.6826 0.91 0.0 0.9 0.0 0.93 0.0 0.92 0.0 0.0131 22.6593 0.91 0.0 0.9 0.0 0.93 0.0 0.92 0.0 0.0127 20.9304 0.91 0.0 0.89 0.0 0.93 0.0
Uruguay 858 0.54 0.0 0.0108 42.2018 0.8 0.0 0.14 0.28 -0.3 0.02 0.5 0.0 0.0108 46.3481 0.78 0.0 0.14 0.29 -0.33 0.01 0.57 0.0 0.0102 40.3532 0.83 0.0 0.15 0.27 -0.27 0.04
Uzbekistan 860 0.7 0.0 0.0053 53.4203 0.72 0.0 0.77 0.0 0.58 0.0 0.7 0.0 0.005 57.0772 0.72 0.0 0.77 0.0 0.59 0.0 0.7 0.0 0.0056 49.8567 0.72 0.0 0.76 0.0 0.57 0.0
Venezuela (Bolivarian Republic of) 862 0.53 0.0 0.011 42.2865 0.08 0.57 0.48 0.0 0.76 0.0 0.53 0.0 0.0125 41.8038 0.03 0.8 0.49 0.0 0.78 0.0 0.53 0.0 0.0097 42.7812 0.13 0.34 0.46 0.0 0.71 0.0
Samoa 882 0.94 0.0 0.0157 26.3516 0.67 0.0 0.94 0.0 0.96 0.0 0.93 0.0 0.0168 26.3465 0.68 0.0 0.92 0.0 0.93 0.0 0.94 0.0 0.0147 26.5948 0.65 0.0 0.95 0.0 0.97 0.0
Yemen 887 0.83 0.0 0.0738 -94.5265 0.8 0.0 0.38 0.0 0.77 0.0 0.82 0.0 0.0716 -87.8487 0.79 0.0 0.37 0.0 0.76 0.0 0.84 0.0 0.0752 -99.7881 0.8 0.0 0.4 0.0 0.77 0.0
Yugoslav SFR 890 0.91 0.0 0.0134 21.4326 -0.13 0.5 0.87 0.0 0.98 0.0 0.91 0.0 0.0148 19.6558 -0.11 0.55 0.87 0.0 0.98 0.0 0.9 0.0 0.0122 22.8158 -0.15 0.43 0.86 0.0 0.99 0.0
Serbia and Montenegro 891 -0.52 0.06 -0.0028 79.6362 -0.5 0.07 -0.56 0.04 -0.24 0.42 -0.42 0.13 -0.0019 80.2814 -0.39 0.17 -0.46 0.1 -0.22 0.45 -0.59 0.03 -0.0036 78.8075 -0.57 0.03 -0.63 0.02 -0.24 0.41
Zambia 894 0.35 0.01 0.0107 29.7942 -0.04 0.79 0.41 0.0 0.85 0.0 0.35 0.01 0.0114 29.789 -0.03 0.82 0.4 0.0 0.85 0.0 0.36 0.0 0.0102 29.2955 -0.03 0.8 0.43 0.0 0.86 0.0

The data for each country will be stored in a Dataframe object.

In [14]:
results_countries = []
results_id = []
results_corr_tlex = []
results_p_tlex = []
results_regr_a_tlex = []
results_regr_b_tlex = []
results_corr_clex = []
results_p_clex = []
results_corr_plex = []
results_p_plex = []
results_corr_flex = []
results_p_flex = []
results_corr_tlexf = []
results_p_tlexf = []
results_regr_a_tlexf = []
results_regr_b_tlexf = []
results_corr_clexf = []
results_p_clexf = []
results_corr_plexf = []
results_p_plexf = []
results_corr_flexf = []
results_p_flexf = []
results_corr_tlexm = []
results_p_tlexm = []
results_regr_a_tlexm = []
results_regr_b_tlexm = []
results_corr_clexm = []
results_p_clexm = []
results_corr_plexm = []
results_p_plexm = []
results_corr_flexm = []
results_p_flexm = []

for key, value in countries_dict.items():
    results_countries.append(value.country_name)
    results_id.append(value.country_id)
    results_corr_tlex.append(value.correlation_tlex) 
    results_p_tlex.append(value.p_value_tlex)
    results_regr_a_tlex.append(value.regr_a_tlex)
    results_regr_b_tlex.append(value.regr_b_tlex)
    results_corr_clex.append(value.correlation_clex) 
    results_p_clex.append(value.p_value_clex)
    results_corr_plex.append(value.correlation_plex) 
    results_p_plex.append(value.p_value_plex)
    results_corr_flex.append(value.correlation_flex) 
    results_p_flex.append(value.p_value_flex)
    results_corr_tlexf.append(value.correlation_tlexf) 
    results_p_tlexf.append(value.p_value_tlexf)
    results_regr_a_tlexf.append(value.regr_a_tlexf)
    results_regr_b_tlexf.append(value.regr_b_tlexf)
    results_corr_clexf.append(value.correlation_clexf) 
    results_p_clexf.append(value.p_value_clexf)
    results_corr_plexf.append(value.correlation_plexf) 
    results_p_plexf.append(value.p_value_plexf)
    results_corr_flexf.append(value.correlation_flexf) 
    results_p_flexf.append(value.p_value_flexf)
    results_corr_tlexm.append(value.correlation_tlexm) 
    results_p_tlexm.append(value.p_value_tlexm)
    results_regr_a_tlexm.append(value.regr_a_tlexm)
    results_regr_b_tlexm.append(value.regr_b_tlexm)
    results_corr_clexm.append(value.correlation_clexm) 
    results_p_clexm.append(value.p_value_clexm)
    results_corr_plexm.append(value.correlation_plexm) 
    results_p_plexm.append(value.p_value_plexm)
    results_corr_flexm.append(value.correlation_flexm) 
    results_p_flexm.append(value.p_value_flexm)

result_df = pd.DataFrame({'country' : results_countries, 'id' : results_id,
                          'corr_tlex' : results_corr_tlex, 'p_tlex' : results_p_tlex,
                          'regr_a_tlex' : results_regr_a_tlex, 'regr_b_tlex' : results_regr_b_tlex,
                          'corr_clex' : results_corr_clex, 'p_clex' : results_p_clex,
                          'corr_plex' : results_corr_plex, 'p_plex' : results_p_plex,
                          'corr_flex' : results_corr_flex, 'p_flex' : results_p_flex,
                          'corr_tlexf' : results_corr_tlexf, 'p_tlexf' : results_p_tlexf,
                          'regr_a_tlexf' : results_regr_a_tlexf, 'regr_b_tlexf' : results_regr_b_tlexf,
                          'corr_clexf' : results_corr_clexf, 'p_clexf' : results_p_clexf,
                          'corr_plexf' : results_corr_plexf, 'p_plexf' : results_p_plexf,
                          'corr_flexf' : results_corr_flexf, 'p_flexf' : results_p_flexf,
                          'corr_tlexm' : results_corr_tlexm, 'p_tlexm' : results_p_tlexm,
                          'regr_a_tlexm' : results_regr_a_tlexm, 'regr_b_tlexm' : results_regr_b_tlexm,
                          'corr_clexm' : results_corr_clexm, 'p_clexm' : results_p_clexm,
                          'corr_plexm' : results_corr_plexm, 'p_plexm' : results_p_plexm,
                          'corr_flexm' : results_corr_flexm, 'p_flexm' : results_p_flexm})

In order to test the correct operation of the code, the attributes of Poland country will be shown.

In [15]:
result_df.loc[result_df['id'] == 616]

,country,id,corr_tlex,p_tlex,regr_a_tlex,regr_b_tlex,corr_clex,p_clex,corr_plex,p_plex,...,corr_tlexm,p_tlexm,regr_a_tlexm,regr_b_tlexm,corr_clexm,p_clexm,corr_plexm,p_plexm,corr_flexm,p_flexm
134,Poland,616,0.16,0.22,0.0057,53.0656,-0.61,0.0,-0.13,0.34,...,0.16,0.23,0.0053,50.4938,-0.53,0.0,-0.14,0.31,0.62,0.0

The results will be saved in countries_stats.csv file.

In [16]:
result_df.to_csv(r'C:\Users\Sebastian\Documents\Data Analyst\Portfolio\1\python_to_bi_countries_stats.csv', index=False)